### ISSUE TITLE
"Unstable" cannot coexists with "Extended fuse"

### ISSUE THREAD

**Issue by Uboaaaaa** [ascpixel/tntweaks#1]
**Describe the bug**
When attempting to extend the fuse duration of an unstable TNT, the crafting result is a regular TNT with extended fuse.

**What is expected**
An... Extended unstable TNT?

**Screenshots**
![1](https://user-images.githubusercontent.com/70588463/116009764-4f4d7d80-a613-11eb-9022-33ba29b54c15.png)
![2](https://user-images.githubusercontent.com/70588463/116009765-507eaa80-a613-11eb-9526-3794f56b7dbb.png)

**Server (please complete the following information):**
 - Server Engine: Paper
 - Minecraft Version: 1.16.5

**Additional information**
The issue bugged me a bit because I set the recipe of an unstable TNT to be this:
![3](https://user-images.githubusercontent.com/70588463/116009861-ae12f700-a613-11eb-945e-293056561439.png)
And that makes it illogical if one can simply convert an unstable TNT into a regular one.

It also means I have to disable tnt-defuse.drop, since the action will indefinitely drop sand or regular TNT instead of soul sand and unstable TNT. Although I do want defusing to return something. (TNT duping has been patched on my server)

**Comment by ascpixel** [comment]
Fixed by commit [c383980](https://github.com/ascpixel/tntweaks/commit/c383980928760676b40f7042db98536948434cbf)
