### ISSUE TITLE
Plugin fails to be loaded after changing the crafting recipe

### ISSUE THREAD

**Issue by Uboaaaaa** [ascpixel/tntweaks#3]
**Describe the bug**
After changing the crafting recipe of unstable TNT, the plugin fails to be loaded.
Config: https://paste.gg/p/anonymous/42208ed354364f96ba274f9fa0a1feee
Error log: https://paste.gg/p/anonymous/ddc491ca58dd45f38bf14662a799f76d

**To Reproduce**
change the _ingredient_ and _shape_ section of the configuration file.

**Server (please complete the following information):**
 - Server Engine: Paper
 - Minecraft Version: 1.16.5

**Comment by ascpixel** [comment]
It turns out that `ConfigurationSection.getValues(boolean).entrySet()` also provides _default_ values... A simple check if the value is actually present in the section with `ignoreDefaults` set to true fixes the issue.
