### ISSUE TITLE
Error: Could not pass event BlockRedstoneEvent

### ISSUE THREAD

**Issue by Uboaaaaa** [ascpixel/tntweaks#5]
**Describe the bug**
https://paste.gg/p/anonymous/0841cd747e65409f9a287ae834db3d39

**To Reproduce**
Place down a detector rail.
Put a minecart on it.

**Server (please complete the following information):**
 - Server Engine: Yatopia
 - Minecraft Version: 1.16.4

**Comment by ascpixel** [comment]
Fixed by commit [ff0a213](https://github.com/ascpixel/tntweaks/commit/ff0a21359734e677a1fe2f4daa0611107dd9223b)

**Comment by Uboaaaaa** [comment]
If the these have been fixed, will there be a release? I'm not familiar with building projects on my own...
