### ISSUE TITLE
A banner for the plugin

### ISSUE THREAD

**Issue by Uboaaaaa** [ascpixel/tntweaks#6]
Really liked the plugin, wanted to contribute but I don't do codes. (；´д｀)ゞ
Here's little something I made for it. 
Please feel free to use.
![Tntweak - Copy](https://user-images.githubusercontent.com/70588463/116639057-87302a00-a95f-11eb-8d40-b0766e43f7ba.png)
![Tntweak - Copy](https://user-images.githubusercontent.com/70588463/116690465-5082ff80-a9b1-11eb-91fa-9391e2099dcb.png)

**Comment by Uboaaaaa** [comment]
![Banner2](https://user-images.githubusercontent.com/70588463/116757649-5ce57780-aa06-11eb-9845-b49e39915fa3.png)
![Tntweakicon](https://user-images.githubusercontent.com/70588463/116757651-5eaf3b00-aa06-11eb-8cf6-8d26af8529f8.png)

**Comment by ascpixel** [comment]
Seems good to me! If you're comfortable with it, please send a pull request with the artwork located in `Resources/Artwork`. This will allow changing the logos in the future by pull requests if necessary, while not having to update existing links.
